Deloy to AWS wit Terraform

on:
  push:
    branches:
      - main
permissions:
    contents: write
    id-token: write
jobs:
  deploy-iac: 
    runs-on: "Self-hosted"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: checkout repository.
        uses: actions/checkout@v2

      - name: setup GitHub OIDC
        run: |
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           unzip awscliv2.zip
           sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli


      - name: configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            # Removed role-to-asume as requested
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}      


      - name: 'Install tfsec for security scanning'
        run: |
          curl -slo tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.1
          chmod +x tfsec
          ./tfsec --version

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt 

      - name: 'Terraform Validate'
        run: terraform validate  

      - name: 'tfsec'
        run: ./tfsec . || true

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform destroy
